version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.16.0
  - dependency-name: "@babel/core"
    versions:
    - 7.13.0
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: webpack
    versions:
    - 5.35.0
  - dependency-name: next
    versions:
    - 10.1.0
